'use strict';

global.PDFLib = require('../lib/pdf-lib.min.js');
const Pdf = require('../core/cdl-pdf.js');

let pass = 0;
let fail = 0;
function check(name, condition) {
  if (condition) pass++;
  else { fail++; console.error('FAIL:', name); }
}

async function run() {
  const png = Buffer.from(
    'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAFgwJ/lq8lWQAAAABJRU5ErkJggg==',
    'base64'
  );
  const prepared = [];
  const progress = [];
  const files = [
    { name: '001.webp', buffer: Buffer.from([1]) },
    { name: '002.png', buffer: png },
  ];
  const bytes = await Pdf.buildChapterPdf(files, {
    metadata: {
      title: 'Series - Ch1',
      subject: 'https://comix.to/title/series/chapter-1',
      author: 'Author',
      keywords: ['Action', 'Drama'],
    },
    async prepareImage(file) {
      prepared.push(file.name);
      return { bytes: png, ext: 'png' };
    },
    onProgress(value) { progress.push(value); },
  });

  const loaded = await global.PDFLib.PDFDocument.load(bytes);
  check('one PDF page is created for every source image', loaded.getPageCount() === 2);
  check('source image order is preserved', prepared.join(',') === '001.webp,002.png');
  check('PDF progress follows the ordered pages',
    progress.slice(0, 2).map((value) => `${value.current}/${value.total}`).join(',') === '1/2,2/2');
  check('PDF progress identifies the otherwise quiet finalization step',
    progress.length === 3 && progress[2].finalizing === true && progress[2].phase === 'finalizing');
  check('chapter title is stored in PDF metadata', loaded.getTitle() === 'Series - Ch1');
  check('chapter author is stored in PDF metadata', loaded.getAuthor() === 'Author');
  check('generated bytes begin with a PDF signature', Buffer.from(bytes).subarray(0, 5).toString() === '%PDF-');
  check('JPEG file extensions normalize for direct embedding',
    Pdf.normalizedExtension({ name: '003.JPEG' }) === 'jpg');

  let emptyError = '';
  try { await Pdf.buildChapterPdf([]); } catch (error) { emptyError = error.message; }
  check('an empty chapter cannot produce a misleading PDF', /No chapter images/i.test(emptyError));

  console.log(`\nRESULT: ${pass} passed, ${fail} failed`);
  if (fail) process.exit(1);
}

run().catch((error) => {
  console.error(error);
  process.exit(1);
});
