'use strict';

const assert = require('assert');
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const read = (relative) => fs.readFileSync(path.join(root, relative), 'utf8');
const Tokens = require('../core/plus-tokens.js');

let passed = 0;
function test(name, fn) {
  try {
    fn();
    passed += 1;
    console.log(`PASS ${name}`);
  } catch (error) {
    console.error(`FAIL ${name}`);
    throw error;
  }
}

const BANNER = '/* Generated by scripts/sync-plus-tokens.mjs from core/plus-tokens.js. Do not edit. */';

test('generated token copies have not drifted from core/plus-tokens.js', () => {
  const expectedCss = BANNER + '\n' + Tokens.css({ scope: ':root' }) + '\n';
  assert.equal(
    read('docs/plus-tokens.css').replace(/\r\n/g, '\n'),
    expectedCss,
    'docs/plus-tokens.css is stale — run node scripts/sync-plus-tokens.mjs'
  );

  // The server code stays in the private repository; the public copy has no Worker tokens.
  if (!fs.existsSync(path.join(__dirname, '..', 'plus-worker'))) return;
  const workerModule = read('plus-worker/plus-tokens.mjs');
  const match = workerModule.match(/export const PLUS_TOKENS_CSS = (".*");/);
  assert.ok(match, 'plus-worker/plus-tokens.mjs must export PLUS_TOKENS_CSS');
  assert.equal(
    JSON.parse(match[1]),
    Tokens.css({ scope: ':root' }),
    'plus-worker/plus-tokens.mjs is stale — run node scripts/sync-plus-tokens.mjs'
  );
});

test('Plus controls are rectangular on every surface', () => {
  assert.equal(Tokens.TOKENS.radius, '0');
  const primitives = Tokens.primitivesCss();
  const literal = primitives.match(/border-radius:\s*(?!var\(--plus-radius\)|0\b)[^;}]+/g) || [];
  assert.deepEqual(literal, [], `primitives must use var(--plus-radius): ${literal.join(', ')}`);
});

test('Plus surfaces carry no light-grey decorative outlines', () => {
  const surfaces = [
    ['core/plus-tokens.js', Tokens.primitivesCss()],
    ['docs/plus-tokens.css', read('docs/plus-tokens.css')]
  ];
  for (const [label, css] of surfaces) {
    assert.doesNotMatch(css, /rgba\(148,\s*163,\s*184/, `${label} still uses the slate-400 decorative border`);
    assert.doesNotMatch(css, /box-shadow:\s*0 \d+px \d+px/, `${label} uses a drop shadow; Plus panels are flat`);
  }
});

test('the extension pane derives its accent ramp from the live comix.to theme', () => {
  const themed = Tokens.tokenCss({ scope: '.cdl-plus', accentFrom: '--accent', inheritFont: true, compact: true });
  assert.match(themed, /--plus-accent: var\(--accent,#8b5cf6\);/);
  assert.match(themed, /--plus-accent-hi: color-mix\(in srgb,var\(--accent,#8b5cf6\) 72%,#ffffff\);/);
  assert.match(themed, /--plus-accent-wash: color-mix\(in srgb,var\(--accent,#8b5cf6\) 13%,transparent\);/);
  assert.match(themed, /--plus-font: inherit;/);
  assert.match(themed, /--plus-control-h: 32px;/);

  // The hosted surfaces are fixed violet; they have no comix.to theme to read.
  const hosted = Tokens.tokenCss({ scope: ':root' });
  assert.match(hosted, /--plus-accent: #8b5cf6;/);
  assert.doesNotMatch(hosted, /color-mix/);
});

test('every primitive is expressed in tokens rather than raw colour', () => {
  const primitives = Tokens.primitivesCss();
  const stray = primitives.match(/#[0-9a-f]{3,8}\b/gi) || [];
  assert.deepEqual(stray, [], `primitives must reference var(--plus-*): ${stray.join(', ')}`);
  const strayRgba = primitives.match(/rgba?\([^)]*\)/gi) || [];
  assert.deepEqual(strayRgba, [], `primitives must reference var(--plus-*): ${strayRgba.join(', ')}`);
});

test('the token set covers every group the Plus surfaces need', () => {
  const groups = Tokens.GROUPS.map((group) => group[0]);
  assert.deepEqual(groups, ['surface', 'text', 'accent', 'status', 'shape', 'type', 'space']);
  for (const name of ['bg', 'panel', 'line', 'text', 'muted', 'accent', 'ok', 'warn', 'danger', 'radius', 'mono', 's4']) {
    assert.ok(Object.prototype.hasOwnProperty.call(Tokens.TOKENS, name), `missing token ${name}`);
  }
});

console.log(`\nRESULT: ${passed} passed, 0 failed`);
